// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqsdLJMN8vk53kgXvGPln05Ir9Sh6vwWI',
    appId: '1:314993143318:web:9eabbd0c35b36a8253cf37',
    messagingSenderId: '314993143318',
    projectId: 'mynotes-flutter-project-a4b40',
    authDomain: 'mynotes-flutter-project-a4b40.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-a4b40.firebasestorage.app',
    measurementId: 'G-5ESV8LBE4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8A5R6IYtHw51PkXgqWgcN5-NSYY5IWVg',
    appId: '1:314993143318:android:b68cf9e8063003d953cf37',
    messagingSenderId: '314993143318',
    projectId: 'mynotes-flutter-project-a4b40',
    storageBucket: 'mynotes-flutter-project-a4b40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUlxMbD_fbLjcGJ39oqgXDSGc3RsMP204',
    appId: '1:314993143318:ios:0bbd7f60ee4dc9bb53cf37',
    messagingSenderId: '314993143318',
    projectId: 'mynotes-flutter-project-a4b40',
    storageBucket: 'mynotes-flutter-project-a4b40.firebasestorage.app',
    iosBundleId: 'com.trainingdomain.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUlxMbD_fbLjcGJ39oqgXDSGc3RsMP204',
    appId: '1:314993143318:ios:0bbd7f60ee4dc9bb53cf37',
    messagingSenderId: '314993143318',
    projectId: 'mynotes-flutter-project-a4b40',
    storageBucket: 'mynotes-flutter-project-a4b40.firebasestorage.app',
    iosBundleId: 'com.trainingdomain.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqsdLJMN8vk53kgXvGPln05Ir9Sh6vwWI',
    appId: '1:314993143318:web:0a4df2e8865b348753cf37',
    messagingSenderId: '314993143318',
    projectId: 'mynotes-flutter-project-a4b40',
    authDomain: 'mynotes-flutter-project-a4b40.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-a4b40.firebasestorage.app',
    measurementId: 'G-C52KHQMPEC',
  );

}